'use client';
import { useEffect,useRef,useState,type CSSProperties,type PointerEvent } from 'react';
import { RotateCcw,Move } from 'lucide-react';
import { rotationFromPointer,clampRotation } from '@/lib/edition-motion';
import { StoryImage } from './story-image';
import { Button } from './ui/button';
const RESTING={rotateX:-4,rotateY:6};
export function TodayEdition({title,href,external,image,date}:{title:string;href:string;external:boolean;image?:string|null;date:string}){
 const [rotation,setRotation]=useState(RESTING);const [reduced,setReduced]=useState(true);const drag=useRef<{x:number;y:number;rotation:typeof RESTING}|null>(null);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{setReduced(q.matches);setRotation(RESTING)};change();q.addEventListener('change',change);return()=>q.removeEventListener('change',change)},[]);
 const move=(e:PointerEvent<HTMLDivElement>)=>{if(reduced)return;if(drag.current){setRotation({rotateX:clampRotation(drag.current.rotation.rotateX-(e.clientY-drag.current.y)/12),rotateY:clampRotation(drag.current.rotation.rotateY+(e.clientX-drag.current.x)/12)});}else if(e.pointerType==='mouse'){const r=e.currentTarget.getBoundingClientRect();setRotation(rotationFromPointer(e.clientX-r.left,e.clientY-r.top,r.width,r.height));}};
 return <div className="edition-interactive"><div className="edition-scene" role="group" tabIndex={0} aria-label="Today's newspaper. Drag or use arrow keys to rotate." style={{'--edition-rotate-x':rotation.rotateX+'deg','--edition-rotate-y':rotation.rotateY+'deg'} as CSSProperties} onPointerMove={move} onPointerDown={e=>{if(reduced)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,rotation}}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}} onPointerLeave={()=>{if(!drag.current&&!reduced)setRotation(RESTING)}} onKeyDown={e=>{if(reduced)return;const values:Record<string,[number,number]>={ArrowLeft:[0,-2],ArrowRight:[0,2],ArrowUp:[-2,0],ArrowDown:[2,0]};const v=values[e.key];if(v){e.preventDefault();setRotation(r=>({rotateX:clampRotation(r.rotateX+v[0]),rotateY:clampRotation(r.rotateY+v[1])}))}}}>
 <div className="edition-stack"><span className="edition-sheet edition-sheet-back" aria-hidden="true"/><span className="edition-sheet edition-sheet-middle" aria-hidden="true"/><div className="edition-sheet edition-sheet-front"><div className="edition-mini-masthead"><span className="wordmark"><span className="wordmark-latin">D</span><span className="wordmark-devanagari">अख़बार</span></span><span className="data-type">Today’s edition</span></div><p className="edition-mini-date data-type">{date}</p><StoryImage src={image} alt="" className="edition-mini-image"/><h2>{title}</h2><div className="edition-mini-columns"><p>Read the reporting behind today’s lead.</p><p>More perspectives. Every source linked.</p></div></div></div></div><div className="edition-controls"><span><Move size={14}/>{reduced?'Today’s edition':'Drag to explore'}</span><Button variant="ghost" size="icon" aria-label="Reset newspaper rotation" onClick={()=>setRotation(RESTING)}><RotateCcw size={16}/></Button><a href={href} target={external?'_blank':undefined} rel={external?'noopener noreferrer':undefined}>Read this story ↗</a></div></div>;
}
