import type { EntityType } from '@prisma/client';

export const ENTITY_SEED: { name: string; type: EntityType; aliases: string[] }[] = [
  { name: 'OpenAI', type: 'company', aliases: ['ChatGPT', 'GPT-4', 'GPT-5'] },
  { name: 'Anthropic', type: 'company', aliases: ['Claude', 'Claude Code'] },
  { name: 'Google', type: 'company', aliases: ['Google AI', 'Google DeepMind', 'Gemini'] },
  { name: 'Microsoft', type: 'company', aliases: ['Microsoft Azure', 'Azure'] },
  { name: 'Apple', type: 'company', aliases: ['Apple Intelligence', 'iOS', 'macOS'] },
  { name: 'Meta', type: 'company', aliases: ['Meta AI', 'Facebook', 'Llama'] },
  { name: 'NVIDIA', type: 'company', aliases: ['Nvidia', 'CUDA'] },
  { name: 'Amazon Web Services', type: 'platform', aliases: ['AWS'] },
  { name: 'Cloudflare', type: 'company', aliases: ['Cloudflare Workers'] },
  { name: 'Vercel', type: 'company', aliases: ['Vercel AI SDK'] },
  { name: 'GitHub', type: 'platform', aliases: ['GitHub Actions', 'GitHub Copilot', 'Copilot'] },
  { name: 'Hacker News', type: 'platform', aliases: ['Y Combinator News'] },
  { name: 'React', type: 'framework', aliases: ['ReactJS', 'React.js', 'React Server Components'] },
  { name: 'Next.js', type: 'framework', aliases: ['NextJS', 'Next JS'] },
  { name: 'Vue.js', type: 'framework', aliases: ['Vue', 'VueJS'] },
  { name: 'Angular', type: 'framework', aliases: ['AngularJS'] },
  { name: 'Svelte', type: 'framework', aliases: ['SvelteKit'] },
  { name: 'Node.js', type: 'technology', aliases: ['NodeJS', 'Node JS'] },
  { name: 'Deno', type: 'technology', aliases: ['Deno Deploy'] },
  { name: 'Bun', type: 'technology', aliases: ['Bun.js'] },
  { name: 'TypeScript', type: 'language', aliases: ['TS'] },
  { name: 'JavaScript', type: 'language', aliases: ['JS', 'ECMAScript'] },
  { name: 'Python', type: 'language', aliases: ['CPython'] },
  { name: 'Rust', type: 'language', aliases: ['Rustlang'] },
  { name: 'Go', type: 'language', aliases: ['Golang', 'Go language'] },
  { name: 'Java', type: 'language', aliases: ['JVM'] },
  { name: 'C++', type: 'language', aliases: ['CPP'] },
  { name: 'PostgreSQL', type: 'database', aliases: ['Postgres', 'PGSQL'] },
  { name: 'MySQL', type: 'database', aliases: ['MariaDB'] },
  { name: 'SQLite', type: 'database', aliases: ['SQLite3'] },
  { name: 'Redis', type: 'database', aliases: ['Valkey'] },
  { name: 'MongoDB', type: 'database', aliases: ['Mongo'] },
  { name: 'Kubernetes', type: 'technology', aliases: ['K8s'] },
  { name: 'Docker', type: 'technology', aliases: ['Docker Desktop', 'Docker Compose'] },
  { name: 'Linux', type: 'platform', aliases: ['GNU/Linux'] },
  { name: 'WebAssembly', type: 'technology', aliases: ['Wasm'] },
  { name: 'Model Context Protocol', type: 'protocol', aliases: ['MCP'] },
  { name: 'GraphQL', type: 'technology', aliases: ['Graph QL'] },
  { name: 'Prisma', type: 'tool', aliases: ['Prisma ORM'] },
  { name: 'Tailwind CSS', type: 'framework', aliases: ['Tailwind', 'TailwindCSS'] },
  { name: 'Terraform', type: 'tool', aliases: ['OpenTofu'] },
  { name: 'PyTorch', type: 'framework', aliases: ['Torch'] },
  { name: 'TensorFlow', type: 'framework', aliases: ['Tensor Flow'] },
  { name: 'Hugging Face', type: 'platform', aliases: ['HuggingFace'] },
  { name: 'Mistral AI', type: 'company', aliases: ['Mistral'] },
  { name: 'DeepSeek', type: 'company', aliases: ['Deep Seek'] },
  { name: 'Supabase', type: 'platform', aliases: ['Supabase Postgres'] },
  { name: 'Stripe', type: 'company', aliases: ['Stripe API'] },
];
